### ISSUE TITLE
Dockerization for Frontend Environment

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#268]
### Issue Description

We need dockerization for our frontend in the project. We aim to enhance the consistency and portability of our frontend application by containerizing them.

### Deadline of the Issue

24.10.2023 - 11:00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

24.10.2023 - 13:00

**Comment by elifkizilky** [comment]
We held a meeting with @yunusemrealtug  and added docker and docker-compose files:

**dockerfile:**
```
FROM node:19
WORKDIR /app
COPY package.json /app/
COPY package-lock.json /app/
RUN npm install
COPY . .
CMD [ "npm", "start" ]
```

**docker-compose:**
```
version: '3.9'

services:
  frontend:
    image: ludos-frontend
    build: .
    command: "npm start"
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
```
 The issue needs to be reviewed now.
